print("Getting to know you!")
print()
myName = input("What's your name? ")
myFavFood = input("What's your favourite food? ")
myFavMusic = input("What's your favourite music? ")
myHome = input("Where do you live? ")
print()
print("You are")
print(myName)
print("You're probably hungry for")
print(myFavFood)
print("and you're definitely getting your groove on to")
print(myFavMusic)
print("living in the amazing ")
print(myHome)
